# fly.toml app configuration file generated for backend-doc-rag on 2025-07-19T00:20:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-doc-rag'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50
  timeout = 300

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.status]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/status"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 30

  [services.tcp_checks]
    interval = "30s"
    timeout = "10s"